export const ADMIN_ROLES = [
  "OWNER",
  "MANAGE_USERS",
  "VIEW_EDITOR_REQUESTS",
  "APPROVE_EDITOR_REQUESTS",
  "VIEW_EDITOR_INFO",
  "SUSPEND_EDITOR",
  "UPDATE_ANY_ARTICLE",
  "DELETE_ANY_ARTICLE",
  "CREATE_ADMIN",
  "VIEW_CRAWLER_LOGS",
  "CONTROL_CRAWLER",
  "MANAGE_EVENTS",
  "APPROVE_PUBLISH_REQUESTS",
  "MANAGE_TELEGRAM_CHANNELS",
  "VIEW_TELEGRAM_POSTS",
  "CONTROL_TELEGRAM_CRAWLER",
  "VIEW_ADMIN_ACTIVITY",
];

export const REGISTERED_ROLE_OPTIONS = [
  "READ_ARTICLE",
  "MANAGE_OWN_PROFILE",
  "REACT_POST",
  "LEAVE_COMMENT",
  "REPORT_POST",
  "CREATE_EDITOR_REQUEST",
];

export const EDITOR_ROLE_OPTIONS = [
  "READ_ARTICLE",
  "MANAGE_OWN_PROFILE",
  "REACT_POST",
  "LEAVE_COMMENT",
  "REPORT_POST",
  "PUBLISH_LIVE_NEWS",
  "EDIT_LIVE_NEWS",
  "DELETE_LIVE_NEWS",
];

export const USER_STATUSES = ["ACTIVE", "PENDING_ACTIVATION", "SUSPENDED"];
